export const shirts = [
  {
    price: 15,
    imageUrl: '/products/blackshirt.png',
    name: 'Solid Black Shirt',
    size: 'M',
    colors: ['black'],
    description: 'A very nice shirt made of cotton for wearing.',
    material: 'cotton',
    available: 10,
  },
  {
    price: 22,
    imageUrl: '/products/greenshirt.png',
    name: 'Green Army Shirt',
    size: 'M',
    colors: ['green'],
    description: 'A very nice shirt made of cotton for wearing.',
    material: 'cotton',
    available: 10,
  },
  {
    price: 9,
    imageUrl: '/products/whiteshirt.png',
    name: 'Plain White Shirt',
    size: 'M',
    colors: ['white'],
    description: 'A very nice shirt made of cotton for wearing.',
    material: 'cotton',
    available: 10,
  },
  {
    price: 18,
    imageUrl: '/products/yellowshirt.png',
    name: 'Plain Yellow Shirt',
    size: 'M',
    colors: ['yellow'],
    description: 'A very nice shirt made of cotton for wearing.',
    material: 'cotton',
    available: 10,
  },
];

export const signs = [
  {
    price: 45,
    imageUrl: '/products/sign1.png',
    name: 'Mountain Sign',
    size: '22in x 16in',
    description: 'A metal sign to hang on your wall showing mountains.',
    material: 'steel',
    available: 10,
  },
  {
    price: 33,
    imageUrl: '/products/sign2.png',
    name: 'Beer Sign',
    size: '16in x 16in',
    description:
      'A metal sign to hang on your wall for your favorite beer drinker.',
    material: 'steel',
    available: 10,
  },
  {
    price: 75,
    imageUrl: '/products/sign3.png',
    name: 'Lion Sign',
    size: '30in x 30in',
    description: 'A metal sign of a lion.',
    material: 'steel',
    available: 10,
  },
  {
    price: 95,
    imageUrl: '/products/sign4.png',
    name: 'Old Sign',
    size: '30in x 16in',
    description: 'An old material sign to hang on your wall.',
    material: 'steel',
    available: 10,
  },
  {
    price: 80,
    imageUrl: '/products/sign5.png',
    name: 'Eagle Gas Sign',
    size: '16in x 16in',
    description: 'A metal sign of Eagle Gas to hang on your wall.',
    material: 'steel',
    available: 10,
  },
  {
    price: 45,
    imageUrl: '/products/sign6.png',
    name: 'Tower Gas',
    size: '16in x 16in',
    description: 'A metal sign of Tower Gas to hang on your wall.',
    material: 'steel',
    available: 10,
  },
];

export const hitches = [
  {
    price: 45,
    imageUrl: '/products/hitch1.png',
    name: 'Nissan Hitch',
    size: '5in x 5in',
    description: 'A Nissan hitch for your truck.',
    material: 'steel',
    available: 10,
  },
  {
    price: 95,
    imageUrl: '/products/hitch2.png',
    name: 'Soccer Hitch',
    size: '6in x 6in',
    description: 'A soccer hitch for your truck.',
    material: 'steel',
    available: 10,
  },
  {
    price: 55,
    imageUrl: '/products/hitch3.png',
    name: 'Flag Hitch',
    size: '8in x 6in',
    description: 'A flag hitch for your truck.',
    material: 'steel',
    available: 10,
  },
  {
    price: 75,
    imageUrl: '/products/hitch4.png',
    name: 'USMC Hitch',
    size: '7in x 7in',
    description: 'A USMC hitch for your truck.',
    material: 'steel',
    available: 10,
  },
];
